config/routes.rb
Rails.application.routes.draw do
  
  resources :portfolios
  resources :stocks, param: :symbol do
    resources :transactions
  end
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :transactions, only: [:index]
    collection do
      get :approvals
    end
    member do
      patch :approve
    end
  end
  
  get "/profile", to: "home#profile", as: "profile"
  resources :home
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  root "home#index"
  get "/landing", to: "home#landing", as: "landing"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate, only: [:landing, :index]

  def index
    if current_user
      redirect_to portfolios_path
    else
      render :landing
    end
  end

  def profile
  end

  def landing
  end
end

app/views/home/home.html.erb
<div class="flex flex-col items-center mt-72 min-h-screen ">
  <div class="flex flex-col ">
    <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
      Welcome to our Journal Planner
    </h1>
    <p class="mb-8 leading-relaxed">
      An easy way to organize your daily journals. Sign in or sign up to begin!
    </p>
    <div class="flex justify-center">
      <%= link_to "Get Started!", sign_in_path, class: "inline-flex text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 shadow-lg shadow-blue-500/50 font-medium rounded-lg text-lg px-5 py-2.5 text-center" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<p class="text-green-500"><%= notice %></p>

<p class="font-medium">Signed in as <%= Current.user.email %></p>

<h2 class="text-xl font-bold mt-4">Login and Verification</h2>

<div class="mt-2">
  <%= link_to "Change password", edit_password_path, class: "text-blue-500 hover:underline" %>
</div>

<div class="mt-2">
  <%= link_to "Change email address", edit_identity_email_path, class: "text-blue-500 hover:underline" %>
</div>

<h2 class="text-xl font-bold mt-4">Access History</h2>

<div class="mt-2">
  <%= link_to "Devices & Sessions", sessions_path, class: "text-blue-500 hover:underline" %>
</div>

<br>

<%= button_to "Log out", Current.session, method: :delete, class: "px-4 py-2 bg-red-500 text-white hover:bg-red-600 transition" %>

app/views/home/landing.html.erb
<section class="h-screen flex flex-col relative overflow-hidden bg-gradient-to-tr from-gray-100 to-gray-300 text-indigo-900">
  <!-- Dynamic Circle Patterns for visual aesthetics -->
  <div class="animate-pulse absolute top-0 left-0 w-48 h-48 bg-indigo-700 rounded-full opacity-20 -translate-x-24 -translate-y-24"></div>
  <div class="animate-pulse absolute bottom-20 right-0 w-64 h-64 bg-indigo-700 rounded-full opacity-20 translate-x-32 translate-y-32"></div>
  <!-- Hero Section - Main Content -->
  <div class="flex-grow flex flex-col justify-center items-center space-y-10 px-6 z-10 relative">
    <h1 class="text-8xl font-extrabold tracking-tighter text-center leading-snug mb-4 bg-clip-text text-transparent bg-gradient-to-br from-indigo-500 to-purple-600 backdrop-blur-md bg-opacity-20 p-4 rounded-xl shadow-md">Stockz</h1>
    <p class="text-2xl font-semibold text-center max-w-2xl leading-relaxed backdrop-blur-md bg-opacity-20 p-6 rounded-lg shadow-md transition-transform transform hover:scale-105">The future of stock trading. Dive into real-time analytics, strategic investments, and a community-driven experience.</p>
    <%= link_to 'Get Started', sign_up_path, class: "mt-5 inline-block bg-gradient-to-br from-indigo-600 to-purple-700 hover:from-indigo-700 hover:to-purple-800 text-white px-10 py-4 rounded-full shadow-2xl transform hover:scale-105 transition-all duration-300" %>
  </div>
  <!-- Footer -->
  <footer class="py-8 text-center space-y-4 bg-indigo-700 text-white">
    <div class="flex justify-center space-x-6">
      <a href="#" class="hover:underline hover:text-purple-400 transition-colors">About Us</a>
      <a href="#" class="hover:underline hover:text-purple-400 transition-colors">Features</a>
      <a href="#" class="hover:underline hover:text-purple-400 transition-colors">Contact</a>
      <a href="#" class="hover:underline hover:text-purple-400 transition-colors">Pricing</a>
    </div>
    <p class="text-sm">© 2023 Stockz. All rights reserved.</p>
  </footer>
</section>

app/views/home/profile.html.erb
<p class="text-green-500"><%= notice %></p>

<p class="font-medium">Signed in as <%= Current.user.email %></p>

<h2 class="text-xl font-bold mt-4">Login and Verification</h2>

<div class="mt-2">
  <%= link_to "Change password", edit_password_path, class: "text-blue-500 hover:underline" %>
</div>

<div class="mt-2">
  <%= link_to "Change email address", edit_identity_email_path, class: "text-blue-500 hover:underline" %>
</div>

<h2 class="text-xl font-bold mt-4">Access History</h2>

<div class="mt-2">
  <%= link_to "Devices & Sessions", sessions_path, class: "text-blue-500 hover:underline" %>
</div>

<br>

<%= button_to "Log out", Current.session, method: :delete, class: "px-4 py-2 bg-red-500 text-white hover:bg-red-600 transition" %>