config/routes.rb
Rails.application.routes.draw do
  
  resources :portfolios
  resources :stocks, param: :symbol do
    resources :transactions
  end
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :transactions, only: [:index]
    collection do
      get :approvals
    end
    member do
      patch :approve
    end
  end
  
  get "/profile", to: "home#profile", as: "profile"
  resources :home
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  root "home#index"
  get "/landing", to: "home#landing", as: "landing"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_flash.html.erb
<div id="flash">
  <% if flash[:notice] %>
    <div class="flash notice bg-green-100 border border-green-400 text-green-700 px-4 py-3 
    rounded relative" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="flash alert bg-red-100 border border-red-400 text-red-700 px-4 py-3 
    rounded relative" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="bg-indigo-700 py-4 shadow-md">
  <nav class="container mx-auto flex justify-between items-center">
    <div>
      <% if current_user %>
        <%= link_to portfolios_path, class: "flex items-center space-x-2" do %>
          <i class="fas fa-chart-line text-white text-xl"></i>
          <span class="text-3xl font-semibold text-white hover:text-indigo-500 transition-colors">Stockz</span>
        <% end %>
      <% else %>
        <%= link_to landing_path, class: "flex items-center space-x-2" do %>
          <i class="fas fa-chart-line text-white text-xl"></i>
          <span class="text-3xl font-semibold text-white hover:text-indigo-500 transition-colors">Stockz</span>
        <% end %>
      <% end %>
    </div>
    <div class="flex items-center space-x-4">
      <!-- Conditional Rendering for Logged Out Users -->
      <% unless current_user %>
        <%= link_to "Sign in", sign_in_path, class: "text-white hover:text-indigo-500 transition px-4 py-2 rounded bg-indigo-600 hover:bg-indigo-800" %>
        <%= link_to "Sign up", sign_up_path, class: "text-white hover:text-indigo-500 transition px-4 py-2 rounded bg-indigo-500 hover:bg-indigo-800" %>
      <% end %>
      <% if current_user %>
        <p class="font-medium text-white hover:text-indigo-500 transition-colors">
          <%= link_to current_user.email, user_path(current_user), class: "hover:underline" %>
        </p>
        <%= button_to "Log out", Current.session, method: :delete, class: "px-4 py-2 bg-red-600 text-white hover:bg-red-700 transition rounded" %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<% if Current.user %>
  <aside class="bg-indigo-800 w-64 flex-none flex flex-col ">
    <ul class="space-y-3 p-4 flex-grow divide-y divide-indigo-700">
      <%= link_to portfolios_path, class: 'block text-white hover:bg-indigo-700 px-4 py-2 rounded transition-colors flex items-center space-x-2' do %>
        <i class="fas fa-tachometer-alt text-lg"></i>
        <span>Portfolio</span>
      <% end %>
      <%= link_to stocks_path, class: 'block text-white hover:bg-indigo-700 px-4 py-2 rounded transition-colors flex items-center space-x-2' do %>
        <i class="fas fa-chart-line text-lg"></i>
        <span>Market</span>
      <% end %>
      <% if current_user %>
        <%= link_to user_transactions_path(current_user), class: 'block text-white hover:bg-indigo-700 px-4 py-2 rounded transition-colors flex items-center space-x-2' do %>
          <i class="fas fa-exchange-alt text-lg"></i>
          <span>Transactions</span>
        <% end %>
      <% end %>
      <% if Current.user.role == "Admin" %>
        <%= link_to users_path, class: 'block text-white hover:bg-indigo-700 px-4 py-2 rounded transition-colors flex items-center space-x-2' do %>
          <i class="fas fa-users text-lg"></i>
          <span>Users</span>
        <% end %>
        <%= link_to approvals_users_path, class: 'block text-white hover:bg-indigo-700 px-4 py-2 rounded transition-colors flex items-center space-x-2' do %>
          <i class="fas fa-check-circle text-lg"></i>
          <span>Approvals</span>
        <% end %>
      <% end %>
    </ul>
  </aside>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  </head>
  <body class="bg-gray-100">
    <body class="bg-gray-100 h-screen flex flex-col">
      <%= render 'layouts/header' %>
      <div class="flex flex-grow">
        <%= render 'layouts/sidebar' %>
        <main class="flex-grow  overflow-y-auto">
          <%= render "layouts/flash" %>
          <%= yield %>
        </main>
      </div>
    </body>
  </html>